### Register User
POST http://localhost:8000/api/auth/register
Content-Type: application/json



### login user
POST http://localhost:8000/api/auth/login
Content-Type: application/json



### get user profile
GET http://localhost:8000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjkyM2M5NGQyYWI5YjNhZWFiM2E4YiIsImlhdCI6MTc0NDM5ODc3NywiZXhwIjoxNzQ1MDAzNTc3fQ.16LxmC0Q_FhbNxirpLfiPK2p97y9PYZEgURtPUeSNp4

### Upload Image
POST http://localhost:8000/api/auth/upload-image
Content-Type: multipart/form-data